# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/best_schedule
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# SPRING SECURITY
# ===============================

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# GRAPHQL
# ===============================
spring.graphql.graphiql.enabled=true

# ===============================
# JWT
# ===============================
jwt.secret=superSecretKeyThatIsVeryLongAndSecure
jwt.expiration=86400000

# ===============================
# LOGGING 
# ===============================
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=DEBUG       
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE 
spring.output.ansi.enabled=ALWAYS
spring.main.banner-mode=off